#!/bin/bash
# FOR LINUX, based off of setup.bat
# go to https://haxe.org/download/linux/ to install the latest version of Haxe
# you may or may not need to run "haxelib setup"
# you may also need to run "chmod +x setup" to mark this file as an executable
haxelib install lime 7.9.0
haxelib install openfl
haxelib install flixel
haxelib install flixel-ui
haxelib install flixel-tools
haxelib install hscript
haxelib install hxCodec
haxelib install newgrounds
haxelib install hxcpp-debug-server
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
haxelib git SScript https://github.com/BeastlyGhost/Forever-SScript
